# Семинар 1

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [4]:
import numpy as np

In [ ]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
vec

In [ ]:
print(vec)

С чем мы работаем?

In [ ]:
vec.dtype

In [ ]:
type(vec)

Размер массива:

In [ ]:
vec.shape

Число осей:

In [ ]:
vec.ndim

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [ ]:
np.sum(vec)

In [ ]:
np.sum(vec, axis=0)

In [ ]:
np.sum(vec, axis=1)

In [ ]:
vec.sum()

Транспонируем массив:

In [ ]:
vec.T

In [ ]:
vec.transpose()

Обратите внимание, что переменная `vec` не поменялась!

In [ ]:
vec

Размеры массивов можно менять:

In [ ]:
vec.reshape(2, 3)

In [ ]:
vec.reshape(-1, 3)

In [ ]:
vec.reshape(2, -1)

Индексирование:

In [ ]:
vec[:, 1]

In [ ]:
vec[2, :]

In [ ]:
vec[1:2, 0]

In [ ]:
vec[::2, :]

Булевы массивы:

In [ ]:
is_even = vec % 2 == 0
print(is_even)

In [ ]:
np.sum(is_even)

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [ ]:
vec[vec % 2 == 0]

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [ ]:
np.zeros((2, 3))

Массив из единиц:

In [ ]:
np.ones((3, 2))

Единичная матрица:

In [ ]:
np.identity(5)

Массивы можно объединять:

In [ ]:
vec

In [ ]:
np.hstack((vec, np.zeros(vec.shape)))

In [ ]:
np.vstack((vec, np.zeros(vec.shape)))

И, наконец - арифметические операции!

In [ ]:
vec + 1

In [ ]:
vec * 2

In [ ]:
vec ** 2

In [ ]:
vec + vec ** 2

In [ ]:
vec * vec ** 2

In [ ]:
np.sin(vec)

Матричное умножение:

In [ ]:
vec.dot(vec ** 2)

In [ ]:
vec.dot((vec ** 2).T)

In [ ]:
vec @ (vec ** 2).T

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [ ]:
vec

In [ ]:
np.arange(3).reshape(3, 1)

In [ ]:
vec + np.arange(3).reshape(3, 1)

Генерация случайных чисел:

In [ ]:
np.random.rand(2, 3)

In [ ]:
np.random.seed(2019)
np.random.rand(2, 3)

In [ ]:
np.random.randn(3, 2)

In [ ]:
np.random.normal(2, 1, size=3)

In [ ]:
np.random.randint(5, 10, size=3)

Почему вообще используют `numpy`?

In [ ]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [ ]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

In [ ]:
%%time
C = A @ B

### Задания для самостоятельного решения

# ┌(▼▼メ)┘ └(メ▼▼)┐

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

    <font size="2" color="#02a82e"> <b>Подсказка #1</b> <i>Полезная функция разделения строк ставишь курсор на начало строки и нажимаешь <b>ctrl + shift + -</b></i></font>

In [117]:
vec = np.array([1, 2, 3, 4, 5])
# С помощью среза:
vec[::-1]

array([5, 4, 3, 2, 1])

In [119]:
# С помощью встроенной функции
np.flip(vec)

array([5, 4, 3, 2, 1])

2. Найти максимальный нечетный элемент в массиве.

In [122]:
# Банальный перебор массива:
vec = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 57, 100, 79])
maxOdd = -1
for elem in vec:
    if elem % 2 == 1 and elem > maxOdd:
        maxOdd = elem
print(maxOdd)

79


In [124]:
# Использование Массива Фильтра
vec = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 57, 100, 79])
filterArr = vec % 2 == 1 # Фильтр работает так, что vec[filterArr] выдает все значения vec в соотвествии с True в filterArr
print(vec[filterArr])
print(max(vec[filterArr]))

[ 1  3  5  7  9 13 57 79]
79


3. Замените все нечетные элементы массива на ваше любимое число.

In [127]:
# Используем np.where
vec = np.array([1, 2, 5, 6, 5, 5, 7, 8])
myFavouriteNumber = 0
res = np.where(vec % 2 == 1, myFavouriteNumber, vec) # По сути поэлементный if else
print(res)

[0 2 0 6 0 0 0 8]


4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [130]:
# Используем np.arange
n = 10
vec = np.arange(2*n - 1, 0, -2)
print(vec)

[19 17 15 13 11  9  7  5  3  1]


5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [133]:
# Используем np.abs, np.argmax, np.argmin
vec = np.array([1, 9, 2, 3, 129, 33, 7, 11, 11, 2, 0, 9])
number = 7
maxDistIndex = np.argmax(np.abs(vec-number)) # argmax ищет индекс наибольшего аргумента на заданной оси (для многомерных работает по осям измерения)
minDistIndex = np.argmin(np.abs(vec-number)) # argmin ищет индекс наименьшего аргумента на заданной оси
print([vec[minDistIndex], vec[maxDistIndex]])

[7, 129]


6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [136]:
# Не используя возможности работы с многочленами в numpy
vec = np.array([1, 1, 1, 1, 1]) # x^4 + x^3 + x^2 + x + 1
dim = len(vec) # размерность
res = np.array([])
for i in range(dim):
    res = np.append(res, vec[i] / (dim - i))
res = np.append(res, -2) # Константа C, можно выбрать любую
print(res)

[ 0.2         0.25        0.33333333  0.5         1.         -2.        ]


In [138]:
# Используем np.polyint
vec = np.array([1, 1, 1, 1, 1]) # x^4 + x^3 + x^2 + x + 1
res = np.polyint(vec)
print(res)

[0.2        0.25       0.33333333 0.5        1.         0.        ]


<font size="2" color="#02a82e"> <b>Подсказка #2</b> <i>Другие функции работы с многочленами:</font>
* np.poly() - по заданным корням строит коэффициенты уравнения
* np.roots() - по заданным коэффициентам находит корни уравнения
* polyadd, polysub, polymul и polydiv добавляют, вычитают, умножают и делят коэффициенты соответственно
* np.polyder() - по заданным коэффициентам считает коэффициенты производной
* np.polyval(arr, x) - подставляет в многочлен с заданными коэффициентами значение
* np.polyfit(x, y, 2) - интерполяция многочлена по заданным точкам

7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [142]:
# Используем np.polyder и np.polyval
vec = np.array([1, 1, 1, 1, 1]) # x^4 + x^3 + x^2 + x + 1
x = 4
res = np.polyval(np.polyder(vec), x)
print(res)

313
